name: json_model_gen
description: >-
  A Dart tool to generate model classes from JSON with fromJson, toJson, copyWith,
  and equality overrides.
version: 0.0.8
homepage: https://github.com/Raagull100/json_model_gen
repository: https://github.com/Raagull100/json_model_gen

topics:
  - json
  - model
  - codegen
  - dart
  - cli

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  recase: ^4.1.0
  args: ^2.4.2

executables:
  json_model_gen:

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
